version: '3.8'

services:
  app:
    build: .
    container_name: danang_investbot
    ports:
      - '3008:3001'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: 123456
      DB_NAME: danang_investbot

  db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: danang_investbot
    ports:
      - '3308:3306'
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
